apiVersion: v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
  matchLabels:
    app: web-app
  template:
    metadata:
      labels:
        app: web-app
        spec:
          containers:
            name: web-app
            image: rickbeniers/adsd-2024-igame:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 8082
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app-service
spec: 
  selector: 
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
